"""
Data models for the Intelligent Research Assistant.
Defines the core data structures used throughout the system.
"""

from dataclasses import dataclass
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum

class ReportStyle(Enum):
    """Available report styles"""
    ACADEMIC = "academic"
    CASUAL = "casual"
    TECHNICAL = "technical"

class ReportLength(Enum):
    """Available report lengths"""
    SHORT = "short"
    MEDIUM = "medium"
    LONG = "long"

class ComplexityLevel(Enum):
    """Query complexity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"

class InformationType(Enum):
    """Types of information being researched"""
    FACTUAL = "factual"
    ANALYTICAL = "analytical"
    CURRENT_EVENTS = "current_events"
    HISTORICAL = "historical"

@dataclass
class ResearchConfig:
    """Configuration for research execution"""
    max_sources: int = 10
    enable_web_scraping: bool = True
    enable_vector_search: bool = True
    report_style: ReportStyle = ReportStyle.ACADEMIC
    report_length: ReportLength = ReportLength.MEDIUM
    timeout_seconds: int = 120

@dataclass
class QueryAnalysis:
    """Analysis of the research query"""
    topic_category: str
    information_type: InformationType
    complexity_level: ComplexityLevel
    estimated_time_minutes: int

@dataclass
class ResearchStrategy:
    """Strategy for conducting research"""
    use_web_search: bool
    use_web_scraping: bool
    use_vector_search: bool
    priority_order: List[str]

@dataclass
class ResearchPlan:
    """Complete research plan generated by Router Agent"""
    query_analysis: QueryAnalysis
    research_strategy: ResearchStrategy
    search_queries: List[str]
    target_websites: List[str]
    expected_challenges: List[str]

@dataclass
class SearchResult:
    """Result from web search"""
    title: str
    url: str
    snippet: str
    credibility_score: float
    source: str  # "serpapi" or "duckduckgo"

@dataclass
class ScrapedContent:
    """Content extracted from web scraping"""
    url: str
    title: str
    content: str
    author: Optional[str] = None
    publish_date: Optional[datetime] = None
    extraction_method: str = "beautifulsoup"  # "beautifulsoup" or "selenium"

@dataclass
class Document:
    """Document from vector database"""
    content: str
    metadata: Dict[str, Any]
    similarity_score: float
    credibility_score: float

@dataclass
class FactCheckResult:
    """Result from fact checking process"""
    verified_facts: List[Dict[str, Any]]
    credibility_scores: Dict[str, float]
    contradictions: List[Dict[str, Any]]
    cleaned_data: List[str]

@dataclass
class ResearchReport:
    """Final research report"""
    executive_summary: str
    key_findings: List[str]
    detailed_analysis: str
    sources: List[str]
    recommendations: List[str]
    metadata: Dict[str, Any]

@dataclass
class ProgressStatus:
    """Progress tracking for research execution"""
    current_step: str
    completion_percentage: float
    estimated_time_remaining: int
    completed_agents: List[str]
    failed_agents: List[str]
    status_message: str

@dataclass
class ResearchResult:
    """Complete result from research execution"""
    query: str
    report: ResearchReport
    metadata: Dict[str, Any]
    execution_time: float
    source_count: int
    success: bool
    error_message: Optional[str] = None